name: CI

on:
  push:
    branches: [ development ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      #Ik wil nog toevoegen dat hij ook mijn container update elke keer als ik een change push. Is dit handig ?
      - name: Run Docker container
        run: |
          docker pull janherscheid/muisvergelijker:1.0
          docker run janherscheid/muisvergelijker:1.0

      - name: Merge changes
        if: success()
        env:
          GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
        run: |
          git config user.name $GIT_USER_NAME
          git config user.email $GIT_USER_EMAIL
          git merge --no-ff ${{ github.event.head.ref }} -m "Merge ${{ github.event.head.ref }} into development"
          git push origin refs/heads/development --quiet "${{ secrets.GIT_TOKEN }}"
