name: CI

on:
  push:
    branches: 
      - main
      - development
  pull_request:
    branches: 
      - main
      - development

env:
  DOTNET_VERSION: '6.0.x'
  IMAGE_NAME: 'janherscheid/muisvergelijker'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build project
      run: dotnet build muisvergelijker/muisvergelijker.sln --configuration Release

    - name: Run tests
      run: dotnet test muisvergelijker/muisvergelijker.sln --verbosity normal --configuration Release

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ env.IMAGE_NAME }}:latest .

    - name: Push Docker image
      run: docker push ${{ env.IMAGE_NAME }}:latest
